/mingw64/bin/cmake . -G"MSYS Makefiles" \
	-DCMAKE_INSTALL_PREFIX="/usr/local" \
	-DCMAKE_BUILD_TYPE=RELEASE -DENABLE_UTILS=OFF \
	-DBUILD_CPP_TESTS=OFF -DBUILD_GTK_TESTS=OFF \
	-DENABLE_QT5=OFF -DENABLE_QT4=OFF -DENABLE_LIBCURL=OFF \
	-DENABLE_GLIB=OFF -DENABLE_XPDF_HEADERS=ON

read test
make -j8
